[build]
  publish = "_site"
  command = "bundle install && bundle exec jekyll build --trace"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.3.0"
  BUNDLER_VERSION = "2.4.10"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self' https://identity.netlify.com https://unpkg.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://unpkg.com https://at.alicdn.com https://cdn.jsdelivr.net; script-src 'self' 'unsafe-inline' https://identity.netlify.com https://unpkg.com https://cdn.jsdelivr.net; img-src 'self' data: https://unpkg.com https://wx.qlogo.cn; font-src 'self' data: https://cdnjs.cloudflare.com https://at.alicdn.com; connect-src 'self' https://wx.qlogo.cn;" 