name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: 代码检查
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 运行ESLint
        run: npm run lint
        
  unit-test:
    name: 单元测试
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 运行单元测试
        run: npm run test:unit
        
      - name: 上传测试覆盖率报告
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
          
      - name: 上传测试结果
        uses: actions/upload-artifact@v3
        with:
          name: unit-test-results
          path: junit.xml
        if: always()
        
  e2e-test:
    name: 端到端测试
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 安装Playwright浏览器
        run: npx playwright install --with-deps
        
      - name: 运行端到端测试
        run: npm run test:e2e
        
      - name: 上传测试结果
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-results
          path: test-results/
        if: always()
        
  build:
    name: 构建
    needs: [lint, unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: 设置Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: 安装依赖
        run: npm ci
        
      - name: 设置Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: 安装Jekyll依赖
        run: bundle install
        
      - name: 构建网站
        run: npm run build
        
      - name: 上传构建产物
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: _site/ 